import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Navigate, Route, Routes, useParams } from "react-router-dom";
import { useState } from "react";
import { useDropzone } from "react-dropzone";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { api } from "../api/client";
import { AlertsPanel, BranchPerformanceTable, BucketOverdueTable, ClosedLoansSection, DisbursementCollectionSection, HighRiskTable, KPIGrid, NewCustomersSection, NPARiskSection, UploadPanel } from "../components/DashboardParts";
const qc = new QueryClient();
const companies = ["supra-pacific", "ideal-supermarket", "cfcici", "central-bazar", "centora", "central-bio-fuel"];
function Login() { return _jsx("div", { className: "p-6", children: "/login" }); }
function CompanySelector() { return _jsx("div", { className: "grid grid-cols-2 gap-3 p-6", children: companies.map((s) => _jsx("a", { className: "border rounded p-4", href: `/${s}`, children: s }, s)) }); }
function CompanyHome() { const { companySlug } = useParams(); return _jsxs("div", { className: "p-6", children: [_jsx("h1", { children: companySlug }), _jsx("a", { href: `/${companySlug}/gold-loan`, children: "Gold Loan" })] }); }
function Placeholder() { return _jsx("div", { className: "p-6", children: "No data yet" }); }
function DashboardPage() { const { companySlug } = useParams(); const [period, setPeriod] = useState("ftd"); const companyId = crypto.randomUUID(); const portfolioType = "gold_loan"; return _jsxs("div", { className: "p-6 space-y-4", children: [_jsx("div", { className: "flex gap-2", children: ["ftd", "mtd", "ytd"].map((p) => _jsx("button", { className: "border px-3 py-1", onClick: () => setPeriod(p), children: p.toUpperCase() }, p)) }), _jsx(KPIGrid, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(DisbursementCollectionSection, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(BucketOverdueTable, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(NewCustomersSection, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(ClosedLoansSection, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(HighRiskTable, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(NPARiskSection, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(BranchPerformanceTable, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(AlertsPanel, { companyId: companyId, portfolioType: portfolioType, period: period }), _jsx(UploadPanel, {})] }); }
function UploadPage() { const [status, setStatus] = useState(""); const dz = useDropzone({ onDrop: async (files) => { const f = files[0]; if (!f)
        return; const fd = new FormData(); fd.append("file", f); fd.append("portfolioId", crypto.randomUUID()); fd.append("statementDate", new Date().toISOString().slice(0, 10)); const r = await api.post("/uploads/loan-balance", fd); const id = r.data.upload_id; const timer = setInterval(async () => { const s = (await api.get(`/uploads/${id}/status`)).data; setStatus(s.status); if (["success", "failed"].includes(s.status))
        clearInterval(timer); }, 3000); } }); return _jsxs("div", { className: "p-6", children: [_jsxs("div", { ...dz.getRootProps(), className: "border-dashed border-2 p-10", children: [_jsx("input", { ...dz.getInputProps() }), "Drop files"] }), _jsx("div", { children: status })] }); }
export default function AppRoutes() {
    return _jsx(QueryClientProvider, { client: qc, children: _jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/", element: _jsx(CompanySelector, {}) }), _jsx(Route, { path: "/:companySlug", element: _jsx(CompanyHome, {}) }), _jsx(Route, { path: "/:companySlug/gold-loan", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "/:companySlug/pledge-loan", element: _jsx(Placeholder, {}) }), _jsx(Route, { path: "/:companySlug/ml-loan", element: _jsx(Placeholder, {}) }), _jsx(Route, { path: "/:companySlug/personal-loan", element: _jsx(Placeholder, {}) }), _jsx(Route, { path: "/:companySlug/vehicle-loan", element: _jsx(Placeholder, {}) }), _jsx(Route, { path: "/upload", element: _jsx(UploadPage, {}) }), _jsx(Route, { path: "/admin/users", element: _jsx("div", { className: 'p-6', children: "Admin users" }) }), _jsx(Route, { path: "/admin/companies", element: _jsx("div", { className: 'p-6', children: "Admin companies" }) }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }) });
}
